name: Test and lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        id: go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Cache build tools
        uses: actions/cache@v4
        with:
          path: |
            bin
          key: ${{ runner.os }}-tools-go${{ steps.go.outputs.go-version }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-go${{ steps.go.outputs.go-version }}-

      - name: Install dependencies
        run: |
          go mod download

      - name: Build project
        run: |
          make build

      - name: Run linters
        run: |
          make lint

      - name: Setup test environment
        run: |
          make test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
          retention-days: 7

      - name: Security scan
        run: |
          make go-security-scan
