name: Test and lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Cache build tools
        uses: actions/cache@v4
        with:
          path: |
            bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install dependencies
        run: |
          go mod download

      - name: Build project
        run: |
          make build

      - name: Run linters
        run: |
          make lint

      - name: Setup test environment
        run: |
          make test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
          retention-days: 7

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    # Run in parallel with build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Run security scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
